version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3005:3005"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - .env

  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    stdin_open: true
    tty: true
    volumes:
      - '.:/web'
      - bundle_cache:/usr/local/bundle
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - .env

volumes:
  redis:
  postgres:
  bundle_cache:
